// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import (
	"github.com/a-h/templ"
	templruntime "github.com/a-h/templ/runtime"
)

func MemorySheetForm() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Create Memory Sheet - Bane</title><link rel=\"stylesheet\" href=\"https://unpkg.com/missing.css@1.0.9/dist/missing.min.css\"></head><body><header><h1>Create New Memory Sheet</h1><nav><a href=\"/memory-sheets\">← Back to Memory Sheets</a></nav></header><main><form action=\"/memory-sheets\" method=\"POST\"><fieldset><legend>Memory Sheet Details</legend> <label for=\"value\">Content <strong>*</strong> <textarea id=\"value\" name=\"value\" rows=\"4\" placeholder=\"Enter the content for your memory sheet...\" required></textarea></label> <small>This is the main content you want to memorize.</small> <label for=\"alias\">Alias (Optional) <input type=\"text\" id=\"alias\" name=\"alias\" placeholder=\"Enter a short description or title...\"></label> <small>A short description to help you identify this memory sheet.</small> <label for=\"date\">Custom Date (Optional) <input type=\"date\" id=\"date\" name=\"date\"></label> <small>Leave empty to use today's date as the starting point.</small></fieldset><button type=\"submit\">Create Memory Sheet</button></form><aside><h2>How Memory Sheets Work</h2><p>Memory sheets use spaced repetition to help you memorize content effectively.  The system will schedule reviews at increasing intervals (1, 1, 5, 7, 14, 19, 30, 50, 60, 80, 100, 120 days)  to optimize long-term retention.</p></aside></main></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
