package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	"github.com/linn221/bane/graph"
	"github.com/linn221/bane/loaders"
	"github.com/linn221/bane/models"
	"github.com/linn221/bane/services"
)

// NewTag is the resolver for the newTag field.
func (r *mutationResolver) NewTag(ctx context.Context, input models.NewTag) (*models.Tag, error) {
	return r.app.Services.TagService.Create(ctx, &input)
}

// PatchTag is the resolver for the patchTag field.
func (r *mutationResolver) PatchTag(ctx context.Context, a string, patch models.PatchInput) (*models.Tag, error) {
	return services.PatchModel[models.Tag](r.DB.WithContext(ctx), r.app.Services.AliasService, a, patch)
}

// DeleteTag is the resolver for the deleteTag field.
func (r *mutationResolver) DeleteTag(ctx context.Context, a string) (*models.Tag, error) {
	return r.app.Services.TagService.Delete(ctx, a)
}

// Tag is the resolver for the tag field.
func (r *queryResolver) Tag(ctx context.Context, a string) (*models.Tag, error) {
	return r.app.Services.TagService.Get(ctx, a)
}

// Tags is the resolver for the tags field.
func (r *queryResolver) Tags(ctx context.Context, search *string) ([]*models.Tag, error) {
	dbctx := r.DB.WithContext(ctx).Model(models.Tag{}).Where("is_active = 1")
	var results []*models.Tag
	err := dbctx.Find(&results).Error
	return results, err
}

// Alias is the resolver for the alias field.
func (r *tagResolver) Alias(ctx context.Context, obj *models.Tag) (string, error) {
	return loaders.GetTagAlias(ctx, obj.Id)
}

// Tag returns graph.TagResolver implementation.
func (r *Resolver) Tag() graph.TagResolver { return &tagResolver{r} }

type tagResolver struct{ *Resolver }
