package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	"github.com/linn221/bane/graph"
	"github.com/linn221/bane/graph/model"
	"github.com/linn221/bane/loaders"
	"github.com/linn221/bane/models"
	"github.com/linn221/bane/services"
)

// Alias is the resolver for the alias field.
func (r *endpointResolver) Alias(ctx context.Context, obj *models.Endpoint) (string, error) {
	return loaders.GetEndpointAlias(ctx, obj.Id)
}

// Match is the resolver for the match field.
func (r *endpointResolver) Match(ctx context.Context, obj *models.Endpoint, regex string) (*model.SearchResult, error) {
	return services.MatchRegex(obj, regex)
}

// Notes is the resolver for the notes field.
func (r *endpointResolver) Notes(ctx context.Context, obj *models.Endpoint) ([]*models.Note, error) {
	var notes []*models.Note
	err := r.app.DB.WithContext(ctx).Where("reference_type = ? AND reference_id = ?", "endpoints", obj.Id).Find(&notes).Error
	return notes, err
}

// NewEndpoint is the resolver for the newEndpoint field.
func (r *mutationResolver) NewEndpoint(ctx context.Context, input models.EndpointInput) (*models.Endpoint, error) {
	return r.app.Services.EndpointService.Create(ctx, &input)
}

// Endpoint is the resolver for the endpoint field.
func (r *queryResolver) Endpoint(ctx context.Context, id *int, alias *string) (*models.Endpoint, error) {
	return r.app.Services.EndpointService.Get(ctx, id, alias)
}

// Endpoints is the resolver for the endpoints field.
func (r *queryResolver) Endpoints(ctx context.Context, filter *models.EndpointFilter) ([]*models.Endpoint, error) {
	return r.app.Services.EndpointService.List(ctx, filter)
}

// Endpoint returns graph.EndpointResolver implementation.
func (r *Resolver) Endpoint() graph.EndpointResolver { return &endpointResolver{r} }

type endpointResolver struct{ *Resolver }
