package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"

	"github.com/linn221/bane/graph"
	"github.com/linn221/bane/graph/model"
	"github.com/linn221/bane/loaders"
	"github.com/linn221/bane/models"
	"github.com/linn221/bane/utils"
)

// Alias is the resolver for the alias field.
func (r *memorySheetResolver) Alias(ctx context.Context, obj *models.MemorySheet) (*string, error) {
	alias, err := loaders.GetMemorySheetAlias(ctx, obj.Id)
	if err != nil {
		return nil, err
	}
	if alias == "" {
		return nil, nil
	}
	return &alias, nil
}

// Notes is the resolver for the notes field.
func (r *memorySheetResolver) Notes(ctx context.Context, obj *models.MemorySheet) ([]*models.Note, error) {
	// TODO: Implement notes relationship when Note model is available
	panic("//2d")
	// return []*model.Note{}, nil
}

// NewMemorySheet is the resolver for the newMemorySheet field.
func (r *mutationResolver) NewMemorySheet(ctx context.Context, input models.MemorySheetInput) (*models.MemorySheet, error) {
	return r.app.Services.MemorySheetService.Create(ctx, &input)
}

// MemorySheet is the resolver for the memorySheet field.
func (r *queryResolver) MemorySheet(ctx context.Context, id *int, alias *string) (*models.MemorySheet, error) {
	if id == nil && alias == nil {
		return nil, fmt.Errorf("either id or alias must be provided")
	}
	if id != nil {
		return r.app.Services.MemorySheetService.Get(ctx, id)
	}
	return nil, fmt.Errorf("alias lookup not yet implemented for MemorySheetService")
}

// MSheets is the resolver for the mSheets field.
func (r *queryResolver) MSheets(ctx context.Context, date *models.MyDate) ([]*models.MemorySheet, error) {
	if date == nil {
		var v models.MyDate
		v.Time = utils.Today()
		date = &v
	}

	return r.app.Services.MemorySheetService.GetTodayNotes(ctx, date.Time)
}

// NextDay is the resolver for the nextDay field.
func (r *todayMemorySheetResolver) NextDay(ctx context.Context, obj *model.TodayMemorySheet) ([]*models.MemorySheet, error) {
	// TODO: Implement next day logic
	return []*models.MemorySheet{}, nil
}

// NextMonth is the resolver for the nextMonth field.
func (r *todayMemorySheetResolver) NextMonth(ctx context.Context, obj *model.TodayMemorySheet) ([]*models.MemorySheet, error) {
	// TODO: Implement next month logic
	return []*models.MemorySheet{}, nil
}

// ThisWeek is the resolver for the thisWeek field.
func (r *todayMemorySheetResolver) ThisWeek(ctx context.Context, obj *model.TodayMemorySheet) ([]*models.MemorySheet, error) {
	// TODO: Implement this week logic
	return []*models.MemorySheet{}, nil
}

// ThisMonth is the resolver for the thisMonth field.
func (r *todayMemorySheetResolver) ThisMonth(ctx context.Context, obj *model.TodayMemorySheet) ([]*models.MemorySheet, error) {
	// TODO: Implement this month logic
	return []*models.MemorySheet{}, nil
}

// MemorySheet returns graph.MemorySheetResolver implementation.
func (r *Resolver) MemorySheet() graph.MemorySheetResolver { return &memorySheetResolver{r} }

// TodayMemorySheet returns graph.TodayMemorySheetResolver implementation.
func (r *Resolver) TodayMemorySheet() graph.TodayMemorySheetResolver {
	return &todayMemorySheetResolver{r}
}

type memorySheetResolver struct{ *Resolver }
type todayMemorySheetResolver struct{ *Resolver }
