package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"

	"github.com/linn221/bane/graph"
	"github.com/linn221/bane/loaders"
	"github.com/linn221/bane/models"
)

// NewMySheet is the resolver for the newMySheet field.
func (r *mutationResolver) NewMySheet(ctx context.Context, input models.MySheetInput) (*models.MySheet, error) {
	return r.app.Services.MySheetService.Create(&input)
}

// Alias is the resolver for the alias field.
func (r *mySheetResolver) Alias(ctx context.Context, obj *models.MySheet) (*string, error) {
	alias, err := loaders.GetMySheetAlias(ctx, obj.Id)
	if err != nil {
		return nil, err
	}
	if alias == "" {
		return nil, nil
	}
	return &alias, nil
}

// Created is the resolver for the created field.
func (r *mySheetResolver) Created(ctx context.Context, obj *models.MySheet) (*models.MyDate, error) {
	myDate := &models.MyDate{Time: obj.Created}
	return myDate, nil
}

// NextDate is the resolver for the nextDate field.
func (r *mySheetResolver) NextDate(ctx context.Context, obj *models.MySheet) (*models.MyDate, error) {
	myDate := &models.MyDate{Time: obj.NextDate}
	return myDate, nil
}

// PreviousDate is the resolver for the previousDate field.
func (r *mySheetResolver) PreviousDate(ctx context.Context, obj *models.MySheet) (*models.MyDate, error) {
	myDate := &models.MyDate{Time: obj.PreviousDate}
	return myDate, nil
}

// Age is the resolver for the age field.
func (r *mySheetResolver) Age(ctx context.Context, obj *models.MySheet) (int, error) {
	// Age is calculated as the number of times the sheet has been reviewed (Index)
	return obj.Index, nil
}

// MySheet is the resolver for the mySheet field.
func (r *queryResolver) MySheet(ctx context.Context, id *int, alias *string) (*models.MySheet, error) {
	if id == nil && alias == nil {
		return nil, fmt.Errorf("either id or alias must be provided")
	}
	return r.app.Services.MySheetService.Get(id, alias)
}

// MySheets is the resolver for the mySheets field.
func (r *queryResolver) MySheets(ctx context.Context, filter *models.MySheetFilter) ([]*models.MySheet, error) {
	if filter != nil && filter.NextDate != nil && !filter.NextDate.Time.IsZero() {
		// If NextDate is provided, use GetTodaySheets logic
		return r.app.Services.MySheetService.GetTodaySheets(filter.NextDate.Time)
	}
	return r.app.Services.MySheetService.List(filter)
}

// MySheet returns graph.MySheetResolver implementation.
func (r *Resolver) MySheet() graph.MySheetResolver { return &mySheetResolver{r} }

type mySheetResolver struct{ *Resolver }
