package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"

	"github.com/linn221/bane/app"
	"github.com/linn221/bane/graph"
	"github.com/linn221/bane/loaders"
	"github.com/linn221/bane/models"
)

// NewProgram is the resolver for the newProgram field.
func (r *mutationResolver) NewProgram(ctx context.Context, input *models.NewProgram) (*models.Program, error) {
	return r.app.Services.ProgramService.Create(input)
}

// UpdateProgram is the resolver for the updateProgram field.
func (r *mutationResolver) UpdateProgram(ctx context.Context, id *int, alias *string, input models.NewProgram) (*models.Program, error) {
	return r.app.Services.ProgramService.Update(id, alias, &input)
}

// PatchProgram is the resolver for the patchProgram field.
func (r *mutationResolver) PatchProgram(ctx context.Context, id *int, alias *string, input models.PatchProgram) (*models.Program, error) {
	// Note: This resolver needs to be updated to use Patch method if we add it to ProgramService
	// For now, using Update as a workaround
	input2 := models.NewProgram{
		Name:        "",
		Alias:       "",
		Description: nil,
		Domain:      "",
		URL:         "",
	}
	if input.Name != nil {
		input2.Name = *input.Name
	}
	if input.Alias != nil {
		input2.Alias = *input.Alias
	}
	if input.Description != nil {
		input2.Description = input.Description
	}
	if input.Domain != nil {
		input2.Domain = *input.Domain
	}
	if input.URL != nil {
		input2.URL = *input.URL
	}
	return r.app.Services.ProgramService.Update(id, alias, &input2)
}

// DeleteProgram is the resolver for the deleteProgram field.
func (r *mutationResolver) DeleteProgram(ctx context.Context, id *int, alias *string) (*models.Program, error) {
	return r.app.Services.ProgramService.Delete(id, alias)
}

// Rid is the resolver for the rid field.
func (r *programResolver) Rid(ctx context.Context, obj *models.Program) (int, error) {
	return loaders.GetRId(ctx, app.Reference{ReferenceId: obj.Id, ReferenceType: "programs"})
}

// Notes is the resolver for the notes field.
func (r *programResolver) Notes(ctx context.Context, obj *models.Program) ([]*models.Note, error) {
	// Use dataloader for efficient Notes loading
	return loaders.GetNotesForProgram(ctx, obj.Id)
}

// Programs is the resolver for the programs field.
func (r *queryResolver) Programs(ctx context.Context, search *string) ([]*models.Program, error) {
	return r.app.Services.ProgramService.List()
}

// Program is the resolver for the program field.
func (r *queryResolver) Program(ctx context.Context, id *int, alias *string) (*models.Program, error) {
	return r.app.Services.ProgramService.Get(id, alias)
}

// Tags is the resolver for the tags field.
func (r *newProgramResolver) Tags(ctx context.Context, obj *models.NewProgram, data []string) error {
	panic(fmt.Errorf("not implemented: Tags - tags"))
}

// Program returns graph.ProgramResolver implementation.
func (r *Resolver) Program() graph.ProgramResolver { return &programResolver{r} }

// NewProgram returns graph.NewProgramResolver implementation.
func (r *Resolver) NewProgram() graph.NewProgramResolver { return &newProgramResolver{r} }

type programResolver struct{ *Resolver }
type newProgramResolver struct{ *Resolver }
