package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	"github.com/linn221/bane/graph"
	"github.com/linn221/bane/loaders"
	"github.com/linn221/bane/models"
)

// NewProject is the resolver for the newProject field.
func (r *mutationResolver) NewProject(ctx context.Context, input models.ProjectInput) (*models.Project, error) {
	return r.app.Services.ProjectService.Create(ctx, &input)
}

// Alias is the resolver for the alias field.
func (r *projectResolver) Alias(ctx context.Context, obj *models.Project) (string, error) {
	return loaders.GetProjectAlias(ctx, obj.Id)
}

// Project is the resolver for the project field.
func (r *queryResolver) Project(ctx context.Context, id *int, alias *string) (*models.Project, error) {
	return r.app.Services.ProjectService.Get(ctx, id, alias)
}

// Projects is the resolver for the projects field.
func (r *queryResolver) Projects(ctx context.Context, filter *models.ProjectFilter) ([]*models.Project, error) {
	return r.app.Services.ProjectService.List(ctx, filter)
}

// Project returns graph.ProjectResolver implementation.
func (r *Resolver) Project() graph.ProjectResolver { return &projectResolver{r} }

type projectResolver struct{ *Resolver }
