package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	"github.com/linn221/bane/graph"
	"github.com/linn221/bane/loaders"
	"github.com/linn221/bane/models"
	"github.com/linn221/bane/services"
)

// CreateTask is the resolver for the createTask field.
func (r *mutationResolver) CreateTask(ctx context.Context, input models.TaskInput) (*models.Task, error) {
	return r.app.Services.TaskService.Create(ctx, &input)
}

// CancelTask is the resolver for the cancelTask field.
func (r *mutationResolver) CancelTask(ctx context.Context, id *int, a *string) (*models.Task, error) {
	return r.app.Services.TaskService.ChangeStatus(ctx, a, id, models.TaskStatusCancelled)
}

// FinishTask is the resolver for the finishTask field.
func (r *mutationResolver) FinishTask(ctx context.Context, id *int, a *string) (*models.Task, error) {
	return r.app.Services.TaskService.ChangeStatus(ctx, a, id, models.TaskStatusFinished)
}

// Task is the resolver for the task field.
func (r *queryResolver) Task(ctx context.Context, a *string) (*models.Task, error) {
	return services.GetRecordByAliasOrId[models.Task](r.app.DB.WithContext(ctx), "tasks", a, nil)
}

// Tasks is the resolver for the tasks field.
func (r *queryResolver) Tasks(ctx context.Context, f *models.TaskFilter) ([]*models.Task, error) {
	return r.app.Services.TaskService.List(ctx, f)
}

// Alias is the resolver for the alias field.
func (r *taskResolver) Alias(ctx context.Context, obj *models.Task) (*string, error) {
	alias, err := loaders.GetTaskAlias(ctx, obj.Id)
	if err != nil {
		return nil, err
	}
	if alias == "" {
		return nil, nil
	}
	return &alias, nil
}

// Task returns graph.TaskResolver implementation.
func (r *Resolver) Task() graph.TaskResolver { return &taskResolver{r} }

type taskResolver struct{ *Resolver }
