package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"

	"github.com/linn221/bane/graph"
	"github.com/linn221/bane/loaders"
	"github.com/linn221/bane/models"
)

// NewTodo is the resolver for the newTodo field.
func (r *mutationResolver) NewTodo(ctx context.Context, input models.TodoInput) (*models.Todo, error) {
	return r.app.Services.TodoService.Create(&input)
}

// Todo is the resolver for the todo field.
func (r *queryResolver) Todo(ctx context.Context, id *int, alias *string) (*models.Todo, error) {
	if id == nil && alias == nil {
		return nil, fmt.Errorf("either id or alias must be provided")
	}
	return r.app.Services.TodoService.Get(id, alias)
}

// Todos is the resolver for the todos field.
func (r *queryResolver) Todos(ctx context.Context, filter *models.TodoFilter) ([]*models.Todo, error) {
	return r.app.Services.TodoService.List(filter)
}

// Deadline is the resolver for the deadline field.
func (r *todoResolver) Deadline(ctx context.Context, obj *models.Todo) (*models.MyDate, error) {
	if obj.Deadline.IsZero() {
		return nil, nil
	}
	myDate := &models.MyDate{Time: obj.Deadline}
	return myDate, nil
}

// Created is the resolver for the created field.
func (r *todoResolver) Created(ctx context.Context, obj *models.Todo) (*models.MyDate, error) {
	myDate := &models.MyDate{Time: obj.Created}
	return myDate, nil
}

// Alias is the resolver for the alias field.
func (r *todoResolver) Alias(ctx context.Context, obj *models.Todo) (*string, error) {
	alias, err := loaders.GetTodoAlias(ctx, obj.Id)
	if err != nil {
		return nil, err
	}
	if alias == "" {
		return nil, nil
	}
	return &alias, nil
}

// Todo returns graph.TodoResolver implementation.
func (r *Resolver) Todo() graph.TodoResolver { return &todoResolver{r} }

type todoResolver struct{ *Resolver }
