package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"

	"github.com/linn221/bane/graph"
	"github.com/linn221/bane/models"
	"github.com/linn221/bane/utils"
)

// NewWord is the resolver for the newWord field.
func (r *mutationResolver) NewWord(ctx context.Context, input models.NewWord) (*models.Word, error) {
	return r.app.Services.WordService.CreateWord(&input)
}

// UpdateWord is the resolver for the updateWord field.
func (r *mutationResolver) UpdateWord(ctx context.Context, id *int, alias *string, input models.NewWord) (*models.Word, error) {
	return r.app.Services.WordService.UpdateWord(id, alias, &input)
}

// PatchWord is the resolver for the patchWord field.
func (r *mutationResolver) PatchWord(ctx context.Context, id *int, alias *string, input models.PatchWord) (*models.Word, error) {
	updates := make(map[string]any)

	if input.Word != nil && *input.Word != "" {
		updates["word"] = *input.Word
	}
	if input.WordType != nil {
		updates["word_type"] = *input.WordType
	}
	if input.Description != nil && *input.Description != "" {
		updates["description"] = *input.Description
	}

	return r.app.Services.WordService.PatchWord(id, alias, updates)
}

// DeleteWord is the resolver for the deleteWord field.
func (r *mutationResolver) DeleteWord(ctx context.Context, id *int, alias *string) (*models.Word, error) {
	return r.app.Services.WordService.DeleteWord(id, alias)
}

// NewWordList is the resolver for the newWordList field.
func (r *mutationResolver) NewWordList(ctx context.Context, input models.NewWordList) (*models.WordList, error) {
	return r.app.Services.WordService.CreateWordList(&input)
}

// UpdateWordList is the resolver for the updateWordList field.
func (r *mutationResolver) UpdateWordList(ctx context.Context, id *int, alias *string, input models.NewWordList) (*models.WordList, error) {
	return r.app.Services.WordService.UpdateWordList(id, alias, &input)
}

// PatchWordList is the resolver for the patchWordList field.
func (r *mutationResolver) PatchWordList(ctx context.Context, id *int, alias *string, input models.PatchWordList) (*models.WordList, error) {
	updates := make(map[string]any)

	if input.Name != nil && *input.Name != "" {
		updates["name"] = *input.Name
	}
	if input.Description != nil && *input.Description != "" {
		updates["description"] = *input.Description
	}

	return r.app.Services.WordService.PatchWordList(id, alias, updates)
}

// DeleteWordList is the resolver for the deleteWordList field.
func (r *mutationResolver) DeleteWordList(ctx context.Context, id *int, alias *string) (*models.WordList, error) {
	return r.app.Services.WordService.DeleteWordList(id, alias)
}

// Word is the resolver for the word field.
func (r *queryResolver) Word(ctx context.Context, id *int, alias *string) (*models.Word, error) {
	return r.app.Services.WordService.GetWord(id, alias)
}

// Words is the resolver for the words field.
func (r *queryResolver) Words(ctx context.Context, search *string) ([]*models.Word, error) {
	var words []*models.Word
	dbctx := r.DB.WithContext(ctx).Model(&models.Word{})
	if search != nil {
		dbctx.Where("word LIKE ?", utils.SurroundPercentages(*search))
	}

	if err := dbctx.Order("word ASC").Find(&words).Error; err != nil {
		return nil, fmt.Errorf("failed to list words: %v", err)
	}
	return words, nil
}

// WordList is the resolver for the wordList field.
func (r *queryResolver) WordList(ctx context.Context, id *int, alias *string) (*models.WordList, error) {
	return r.app.Services.WordService.GetWordList(id, alias)
}

// WordLists is the resolver for the wordLists field.
func (r *queryResolver) WordLists(ctx context.Context, regex *string) ([]*models.AllWordList, error) {
	panic(fmt.Errorf("not implemented: WordLists - wordLists"))
}

// ImportURL is the resolver for the importUrl field.
func (r *wordListResolver) ImportURL(ctx context.Context, obj *models.WordList) (*string, error) {
	url := fmt.Sprintf("/importWordlist/%d", obj.Id)
	return &url, nil
}

// WordList returns graph.WordListResolver implementation.
func (r *Resolver) WordList() graph.WordListResolver { return &wordListResolver{r} }

type wordListResolver struct{ *Resolver }
