package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"

	"github.com/linn221/bane/graph"
	"github.com/linn221/bane/loaders"
	"github.com/linn221/bane/models"
	"github.com/linn221/bane/utils"
)

// NewWord is the resolver for the newWord field.
func (r *mutationResolver) NewWord(ctx context.Context, input models.WordInput) (*models.Word, error) {
	return r.app.Services.WordService.CreateWord(&input)
}

// NewWordList is the resolver for the newWordList field.
func (r *mutationResolver) NewWordList(ctx context.Context, input models.WordListInput) (*models.WordList, error) {
	return r.app.Services.WordService.CreateWordList(&input)
}

// Word is the resolver for the word field.
func (r *queryResolver) Word(ctx context.Context, id *int, alias *string) (*models.Word, error) {
	return r.app.Services.WordService.GetWord(id, alias)
}

// Words is the resolver for the words field.
func (r *queryResolver) Words(ctx context.Context, search *string) ([]*models.Word, error) {
	var words []*models.Word
	dbctx := r.DB.WithContext(ctx).Model(&models.Word{})
	if search != nil {
		dbctx.Where("word LIKE ?", utils.SurroundPercentages(*search))
	}

	if err := dbctx.Order("word ASC").Find(&words).Error; err != nil {
		return nil, fmt.Errorf("failed to list words: %v", err)
	}
	return words, nil
}

// WordList is the resolver for the wordList field.
func (r *queryResolver) WordList(ctx context.Context, id *int, alias *string) (*models.WordList, error) {
	return r.app.Services.WordService.GetWordList(id, alias)
}

// WordLists is the resolver for the wordLists field.
func (r *queryResolver) WordLists(ctx context.Context, regex *string) ([]*models.AllWordList, error) {
	panic(fmt.Errorf("not implemented: WordLists - wordLists"))
}

// Alias is the resolver for the alias field.
func (r *wordResolver) Alias(ctx context.Context, obj *models.Word) (*string, error) {
	alias, err := loaders.GetWordAlias(ctx, obj.Id)
	if err != nil {
		return nil, err
	}
	if alias == "" {
		return nil, nil
	}
	return &alias, nil
}

// Alias is the resolver for the alias field.
func (r *wordListResolver) Alias(ctx context.Context, obj *models.WordList) (*string, error) {
	alias, err := loaders.GetWordListAlias(ctx, obj.Id)
	if err != nil {
		return nil, err
	}
	if alias == "" {
		return nil, nil
	}
	return &alias, nil
}

// ImportURL is the resolver for the importUrl field.
func (r *wordListResolver) ImportURL(ctx context.Context, obj *models.WordList) (*string, error) {
	url := fmt.Sprintf("/importWordlist/%d", obj.Id)
	return &url, nil
}

// Word returns graph.WordResolver implementation.
func (r *Resolver) Word() graph.WordResolver { return &wordResolver{r} }

// WordList returns graph.WordListResolver implementation.
func (r *Resolver) WordList() graph.WordListResolver { return &wordListResolver{r} }

type wordResolver struct{ *Resolver }
type wordListResolver struct{ *Resolver }
