// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/linn221/bane/models"
)

type Mutation struct {
}

type Query struct {
}

type SQL struct {
	DelID  *SQLResult `json:"delId,omitempty"`
	DelRid *SQLResult `json:"delRid,omitempty"`
	Del    *SQLResult `json:"del,omitempty"`
	Count  *SQLResult `json:"count,omitempty"`
}

type SQLResult struct {
	Success bool `json:"success"`
	Count   int  `json:"count"`
}

type SearchResult struct {
	Results []string `json:"results,omitempty"`
	Count   *int     `json:"count,omitempty"`
}

type TaskFilter struct {
	Today      *bool              `json:"today,omitempty"`
	Search     *string            `json:"search,omitempty"`
	Status     *models.TaskStatus `json:"status,omitempty"`
	Project    *string            `json:"project,omitempty"`
	Created    *models.MyDate     `json:"created,omitempty"`
	Deadline   *models.MyDate     `json:"deadline,omitempty"`
	RemindDate *models.MyDate     `json:"remindDate,omitempty"`
}

type TodayMemorySheet struct {
	Today     models.MyDate         `json:"today"`
	Sheets    []*models.MemorySheet `json:"sheets"`
	NextDay   []*models.MemorySheet `json:"nextDay"`
	NextMonth []*models.MemorySheet `json:"nextMonth"`
	ThisWeek  []*models.MemorySheet `json:"thisWeek"`
	ThisMonth []*models.MemorySheet `json:"thisMonth"`
}
