// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/linn221/bane/models"
)

type Download struct {
	URL string `json:"url"`
}

type Mutation struct {
}

type NewNote struct {
	Value string `json:"value"`
}

type Note struct {
	Value     string        `json:"value"`
	Match     *SearchResult `json:"match"`
	CreatedAt models.MyTime `json:"createdAt"`
	UpdatedAt models.MyTime `json:"updatedAt"`
}

type Query struct {
}

type SearchResult struct {
	Results []string `json:"results,omitempty"`
	Count   *int     `json:"count,omitempty"`
}

type TodayMemorySheet struct {
	Today     models.MyDate         `json:"today"`
	Sheets    []*models.MemorySheet `json:"sheets"`
	NextDay   []*models.MemorySheet `json:"nextDay"`
	NextMonth []*models.MemorySheet `json:"nextMonth"`
	ThisWeek  []*models.MemorySheet `json:"thisWeek"`
	ThisMonth []*models.MemorySheet `json:"thisMonth"`
}
